const actionTypes = Object.freeze({
 //app
 APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
 SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
 TOGGLE_LOADING: 'TOGGLE_LOADING',

 //user
 SUCCEEDED_USER_LOGIN: 'SUCCEEDED_USER_LOGIN',
 FAILED_USER_LOGIN: 'FAILED_USER_LOGIN',

 SUCCEEDED_GET_ALL_USERS: 'SUCCEEDED_GET_ALL_USERS',
 FAILED_GET_ALL_USERS: 'FAILED_GET_ALL_USERS',
});

export default actionTypes;
