const actionTypes = Object.freeze({
 //app
 APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
 SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
 TOGGLE_LOADING: 'TOGGLE_LOADING',

 //user
 SUCCEEDED_USER_LOGIN: 'SUCCEEDED_USER_LOGIN',
 FAILED_USER_LOGIN: 'FAILED_USER_LOGIN',

 SUCCEEDED_CREATE_ACCOUNT: 'SUCCEEDED_CREATE_ACCOUNT',
 FAILED_CREATE_ACCOUNT: 'FAILED_CREATE_ACCOUNT',

 //admin
 SUCCEEDED_GET_ALL_USERS: 'SUCCEEDED_GET_ALL_USERS',
 FAILED_GET_ALL_USERS: 'FAILED_GET_ALL_USERS',

 SUCCEEDED_GET_AN_USER_BY_ID: 'SUCCEEDED_GET_AN_USER_BY_ID',
 FAILED_GET_AN_USER_BY_ID: 'FAILED_GET_AN_USER_BY_ID',

 SUCCEEDED_UPDATE_AN_USER: 'SUCCEEDED_UPDATE_AN_USER',
 FAILED_UPDATE_AN_USER: 'FAILED_UPDATE_AN_USER',
});

export default actionTypes;
