const actionTypes = Object.freeze({
	//app
	APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
	SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',
	TOGGLE_LOADING: 'TOGGLE_LOADING',

	//user
	SUCCEEDED_USER_LOGIN: 'SUCCEEDED_USER_LOGIN',
	FAILED_USER_LOGIN: 'FAILED_USER_LOGIN',

	SUCCEEDED_USER_LOGIN_GG: 'SUCCEEDED_USER_LOGIN_GG',
	FAILED_USER_LOGIN_GG: 'FAILED_USER_LOGIN_GG',

	SUCCEEDED_USER_LOGOUT: 'SUCCEEDED_USER_LOGOUT',
	FAILED_USER_LOGOUT: 'FAILED_USER_LOGOUT',

	//admin
	SUCCEEDED_GET_ALL_USERS: 'SUCCEEDED_GET_ALL_USERS',
	FAILED_GET_ALL_USERS: 'FAILED_GET_ALL_USERS',

	SUCCEEDED_GET_AN_USER_BY_ID: 'SUCCEEDED_GET_AN_USER_BY_ID',
	FAILED_GET_AN_USER_BY_ID: 'FAILED_GET_AN_USER_BY_ID',

	SUCCEEDED_UPDATE_AN_USER: 'SUCCEEDED_UPDATE_AN_USER',
	FAILED_UPDATE_AN_USER: 'FAILED_UPDATE_AN_USER',

	SUCCEEDED_CREATE_ACCOUNT: 'SUCCEEDED_CREATE_ACCOUNT',
	FAILED_CREATE_ACCOUNT: 'FAILED_CREATE_ACCOUNT',

	SUCCEEDED_DELETE_BY_ID: 'SUCCEEDED_DELETE_BY_ID',
	FAILED_DELETE_BY_ID: 'FAILED_DELETE_BY_ID',

	SUCCEEDED_GET_USER_ALLCODES: 'SUCCEEDED_GET_USER_ALLCODES',
	FAILED_GET_USER_ALLCODES: 'FAILED_GET_USER_ALLCODES',

	SUCCEEDED_GET_ALL_DOCTORS: 'SUCCEEDED_GET_ALL_DOCTORS',
	FAILED_GET_ALL_DOCTORS: 'FAILED_GET_ALL_DOCTORS',

	SUCCEEDED_CREATE_DOCTOR_MARKDOWN: 'SUCCEEDED_CREATE_DOCTOR_MARKDOWN',
	FAILED_CREATE_DOCTOR_MARKDOWN: 'FAILED_CREATE_DOCTOR_MARKDOWN',

	SUCCEEDED_GET_DOCTOR_CONTENT: 'SUCCEEDED_GET_DOCTOR_CONTENT',
	FAILED_GET_DOCTOR_CONTENT: 'FAILED_GET_DOCTOR_CONTENT',

	SUCCEEDED_GET_DOCTOR_INFO: 'SUCCEEDED_GET_DOCTOR_INFO',
	FAILED_GET_DOCTOR_INFO: 'FAILED_GET_DOCTOR_INFO',

	SUCCEEDED_GET_DOCTOR_INTRO: 'SUCCEEDED_GET_DOCTOR_INTRO',
	FAILED_GET_DOCTOR_INTRO: 'FAILED_GET_DOCTOR_INTRO',

	SUCCEEDED_GET_DOCTOR_MARKDOWN: 'SUCCEEDED_GET_DOCTOR_MARKDOWN',
	FAILED_GET_DOCTOR_MARKDOWN: 'FAILED_GET_DOCTOR_MARKDOWN',

	SUCCEEDED_GET_SCHEDULE_RANGE: 'SUCCEEDED_GET_SCHEDULE_RANGE',
	FAILED_GET_SCHEDULE_RANGE: 'FAILED_GET_SCHEDULE_RANGE',

	SUCCEEDED_CREATE_DOCTOR_SCHEDULE: 'SUCCEEDED_CREATE_DOCTOR_SCHEDULE',
	FAILED_CREATE_DOCTOR_SCHEDULE: 'FAILED_CREATE_DOCTOR_SCHEDULE',

	SUCCEEDED_GET_DOCTOR_SCHEDULE_BY_INFO: 'SUCCEEDED_GET_DOCTOR_SCHEDULE_BY_INFO',
	FAILED_GET_DOCTOR_SCHEDULE_BY_INFO: 'FAILED_GET_DOCTOR_SCHEDULE_BY_INFO',

	SUCCEEDED_GET_DOCTOR_WORKDATE_BY_ID: 'SUCCEEDED_GET_DOCTOR_WORKDATE_BY_ID',
	FAILED_GET_DOCTOR_WORKDATE_BY_ID: 'FAILED_GET_DOCTOR_WORKDATE_BY_ID',

	SUCCEEDED_GET_ALLCODES_EXTRA: 'SUCCEEDED_GET_ALLCODES_EXTRA',
	FAILED_GET_ALLCODES_EXTRA: 'FAILED_GET_ALLCODES_EXTRA',

	SUCCEEDED_CREATE_DOCTOR_EXTRA_INFO_BYID: 'SUCCEEDED_CREATE_DOCTOR_EXTRA_INFO_BYID',
	FAILED_CREATE_DOCTOR_EXTRA_INFO_BYID: 'FAILED_CREATE_DOCTOR_EXTRA_INFO_BYID',

	SUCCEEDED_GET_DOCTOR_EXTRA_INFO_BY_ID: 'SUCCEEDED_GET_DOCTOR_EXTRA_INFO_BY_ID',
	FAILED_GET_DOCTOR_EXTRA_INFO_BY_ID: 'FAILED_GET_DOCTOR_EXTRA_INFO_BY_ID',

	SUCCEEDED_GET_DOCTOR_EXTRA_INFO_BY_ID_FOR_UI: 'SUCCEEDED_GET_DOCTOR_EXTRA_INFO_BY_ID_FOR_UI',
	FAILED_GET_DOCTOR_EXTRA_INFO_BY_ID_FOR_UI: 'FAILED_GET_DOCTOR_EXTRA_INFO_BY_ID_FOR_UI',

	SUCCEEDED_CREATE_BOOKING_ACC: 'SUCCEEDED_CREATE_BOOKING_BY_DOCTOR_ID',
	FAILED_CREATE_BOOKING_ACC: 'FAILED_CREATE_BOOKING_BY_DOCTOR_ID',

	SUCCEEDED_PATIENT_TOKEN_CONFIRM: 'SUCCEEDED_PATIENT_TOKEN_CONFIRM',
	FAILED_PATIENT_TOKEN_CONFIRM: 'FAILED_PATIENT_TOKEN_CONFIRM',

	SUCCEEDED_GET_ALL_SPECIALITIES: 'SUCCEEDED_GET_ALL_SPECIALITIES',
	FAILED_GET_ALL_SPECIALITIES: 'FAILED_GET_ALL_SPECIALITIES',

	SUCCEEDED_GET_SPECIALITY_AND_DOCTOR_BYID: 'SUCCEEDED_GET_SPECIALITY_AND_DOCTOR_BYID',
	FAILED_GET_SPECIALITY_AND_DOCTOR_BYID: 'FAILED_GET_SPECIALITY_AND_DOCTOR_BYID',

	SUCCEEDED_CREATE_CLINIC: 'SUCCEEDED_CREATE_CLINIC',
	FAILED_CREATE_CLINIC: 'FAILED_CREATE_CLINIC',

	SUCCEEDED_GET_ALL_CLINICS: 'SUCCEEDED_GET_ALL_CLINICS',
	FAILED_GET_ALL_CLINICS: 'FAILED_GET_ALL_CLINICS',

	SUCCEEDED_GET_CLINIC_LIST: 'SUCCEEDED_GET_CLINIC_LIST',
	FAILED_GET_CLINIC_LIST: 'FAILED_GET_CLINIC_LIST',

	SUCCEEDED_GET_CLINIC_BY_ID: 'SUCCEEDED_GET_CLINIC_BY_ID',
	FAILED_GET_CLINIC_BY_ID: 'FAILED_GET_CLINIC_BY_ID',

	SUCCEEDED_GET_PATIENT_MANAGER_BY_DOCTOR_ID: 'SUCCEEDED_GET_PATIENT_MANAGER_BY_DOCTOR_ID',
	FAILED_GET_PATIENT_MANAGER_BY_DOCTOR_ID: 'FAILED_GET_PATIENT_MANAGER_BY_DOCTOR_ID',
});

export default actionTypes;
