const actionTypes = Object.freeze({
 //app
 APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
 SWITCH_LANGUAGE: 'SWITCH_LANGUAGE',

 //user
 SUCCEEDED_USER_LOGIN: 'SUCCEEDED_USER_LOGIN',
 FAILED_USER_LOGIN: 'FAILED_USER_LOGIN',
});

export default actionTypes;
